const reminderListEl = document.getElementById("reminder-list");
const alarmListEl = document.getElementById("alarm-list");

function renderScheduleList(container, entries, { subtitle, onDelete }) {
  container.innerHTML = "";
  if (entries.length === 0) {
    const hint = document.createElement("div");
    hint.className = "memory-empty-hint";
    hint.textContent = "None set yet.";
    container.appendChild(hint);
    return;
  }
  for (const entry of entries) {
    const item = document.createElement("div");
    item.className = "memory-item";

    const text = document.createElement("div");
    text.className = "memory-item-text";
    text.textContent = entry.message;

    const tag = document.createElement("div");
    tag.className = "memory-item-tag";
    tag.textContent = `${entry.process} — ${subtitle(entry)}`;

    const deleteBtn = document.createElement("button");
    deleteBtn.className = "memory-item-delete";
    deleteBtn.textContent = "×";
    deleteBtn.title = "Remove";
    deleteBtn.addEventListener("click", () => onDelete(entry));

    item.appendChild(text);
    item.appendChild(tag);
    item.appendChild(deleteBtn);
    container.appendChild(item);
  }
}

async function loadReminders() {
  const entries = await fetch("/api/reminders").then((r) => r.json());
  renderScheduleList(reminderListEl, entries, {
    subtitle: (e) => `every ${e.interval_minutes} min`,
    onDelete: async (entry) => {
      const response = await fetch(`/api/reminders/${entry.id}`, { method: "DELETE" });
      if (response.ok) await loadReminders();
    },
  });
}

async function loadAlarms() {
  const entries = await fetch("/api/reminders/alarms").then((r) => r.json());
  renderScheduleList(alarmListEl, entries, {
    subtitle: (e) => new Date(e.fire_at).toLocaleString(),
    onDelete: async (entry) => {
      const response = await fetch(`/api/reminders/alarms/${entry.id}`, { method: "DELETE" });
      if (response.ok) await loadAlarms();
    },
  });
}

// Fired reminders/alarms land in a small backend-side pending queue (generated by a background
// LLM pass, entirely outside the normal chat request/response cycle) - poll for them and, the
// moment one shows up, inject it into whichever chat is currently open as if the companion just
// spoke up unprompted, then ack it so it isn't shown twice.
async function checkPendingReminders() {
  let pending;
  try {
    pending = await fetch("/api/reminders/pending").then((r) => r.json());
  } catch (err) {
    return; // transient server hiccup - the next poll tick will catch up
  }
  if (pending.length === 0) return;

  // With lazy chat creation there's often no active chat (app idling on the empty state) -
  // a fired reminder must still be spoken and kept, not acked into the void, so open a chat
  // for it the same way sending a message would.
  if (!getActiveChat()) {
    exitEmptyState();
    createNewChat();
  }
  const chat = getActiveChat();
  const narrateEnabled = document.getElementById("cfg-narrate").checked;

  for (const item of pending) {
    appendMessage("assistant", item.text, null, true);
    addMessageToChat(chat, "assistant", item.text);
    if (narrateEnabled) enqueueNarration(item.text);
    await fetch(`/api/reminders/pending/${item.id}`, { method: "DELETE" }).catch(() => {});
  }
}

setInterval(checkPendingReminders, 20000);
checkPendingReminders();

// --- Game State floating panel ---
// Ephemeral, background-OCR-derived snapshot of what's happening in-game right now. Distinct
// from Memory: this never gets written to disk, it just reflects the current session. Shown
// automatically while a game is being tracked, hidden otherwise - no manual toggle button.

